config/routes.rb
Shuttleshare::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => 'rides#index'

  resources :rides do
    collection do
      get 'join'
      get 'leave'
      get 'airport'
      get 'aspc_rides'
    end

    resources :comments
  end

  resources :users do
    collection do
      get 'unsubscribe'
      get 'login'
    end
  end

  scope controller: :sessions do
    get   'unauthorized' => :not_authorized
    get   'login' => :new
    match 'logout' => :destroy, :via => [:get, :destroy]
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  post 'mailer/comment'

  #match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ride
  belongs_to :user

  def get_user
    user = User.find_by(id: self.user_id)
    unless user.nil?
      return user.name
    end
    return ""
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :login_helper, :only => [:create, :destroy]

  def create
    @ride = Ride.find(params[:ride_id])
    @comment = @ride.comments.create(params[:comment].permit("comment", "commit", "ride_id", "user_id"))
    redirect_to ride_path(@ride)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @ride = @comment.ride

    if @comment.user_id == @current_user.id
      @comment.destroy
    end

    redirect_to ride_path(@ride)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p class="help">
  <span class="tag is-pulled-right"><%= comment.user.email %></span>
  <% if comment.user.phone_number %>
    <span class="tag is-pulled-right"><%= comment.user.phone_number %></span>
  <% end %>
  <span class="tag is-info is-pulled-right">
    Posted by <%= comment.user.name %>
    <% if @current_user and comment.user_id == @current_user.id %>
      <%= link_to '', ride_comment_path(comment.ride_id, comment.id), :method => :delete, :class=> "delete is-small"  %>
    <%end %>
  </span>
</p>
<p>
  <%= comment.comment %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@ride, @ride.comments.build]) do |f| %>
  <%= f.text_area :comment, :class => "textarea", :placeholder => "Any comment you post will be public" %>
  <%= f.hidden_field :user_id, :value => @current_user.id %>
  <br />

  <%= f.submit "Post comment", :class => "button is-light is-small" %>
<% end %>