config/routes.rb
Shuttleshare::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => 'rides#index'

  resources :rides do
    collection do
      get 'join'
      get 'leave'
      get 'airport'
      get 'aspc_rides'
    end

    resources :comments
  end

  resources :users do
    collection do
      get 'unsubscribe'
      get 'login'
    end
  end

  scope controller: :sessions do
    get   'unauthorized' => :not_authorized
    get   'login' => :new
    match 'logout' => :destroy, :via => [:get, :destroy]
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  post 'mailer/comment'

  #match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rides_users
  has_many :rides, :through => :rides_users

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validate :is_password_necessary

  enum school: [ :unknown, :pomona, :claremont_mckenna, :harvey_mudd, :scripps, :pitzer ]

  def is_password_necessary
    return if is_cas_authenticated

    if password.blank?
      errors.add(:password, 'needs to be present if is_cas_authenticated is false')
    end
  end

  def self.find_from_hash(hash)
    user = find_by_fb_id(hash['uid'])
    if user
      unless user.email
        user.email = hash[:info][:email]
        user.save
      end
    end
    user
  end

  def self.find_or_create_by_clef_id(response)
    puts response['info']
    if user = find_by_clef_id(response['info']['id'].to_s)
      user
    elsif user = find_by_email(response['info']['email'])
      user.clef_id = response['info']['id']
      user.save
    else
      user = create :name => (response['info']['first_name'] + " " + response['info']['last_name']),
                    :clef_id => response['info']['id'].to_s,
                    :email => response['info']['email'],
                    :fbimage => 'http://files.sharenator.com/awesome_face_151_U_WANT_CUTE-s580x580-92380-580.png'
    end
    user
  end

  def self.create_from_hash!(hash)
    create :name => hash['info'][:name], :fb_id => hash[:uid], :fbimage => hash['info'][:image], :fblink => hash['info'][:urls][:Facebook],:email => hash['info'][:email]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :correct_user, :only => [:edit, :show]

  def edit
    @title = "5C Rideshare :: settings"
  end

  def update
    if @current_user.update_attributes(user_params)
      redirect_to edit_user_path(@current_user), :notice => "Your user information was successfully updated."
    else
      redirect_to :action => 'edit'
    end
  end

  def show
    @title = "5C Rideshare :: your rides"
    rides = @current_user.rides
    @arrivals = []
    @departures = []
    rides.each do |ride|
      if ride.airport == "From Ontario" or ride.airport == "From LAX"
        @arrivals << ride
      else
        @departures << ride
      end
    end
    @arrivals = sort_rides(@arrivals)
    @departures = sort_rides(@departures)
  end

  def unsubscribe
    email = params[:id]
    if email
      user = User.find_by_email(email)
      if user
        user.email_pref = false
        user.save
        redirect_to root_url, :notice => "Successfully unsubscribed from email notifications"
      else
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end

  protected

    helper_method :correct_user

    def correct_user
      redirect_to root_url unless @current_user && params[:id] == @current_user.id.to_s
    end

    def user_params
      if params[:user]
        params.require(:user).permit(:name, :email, :email_pref)
      end
    end
end

app/views/users/edit.html.haml
=content_for :header do
  =render 'layouts/page_header', :title => "Account Preferences"


#edit-user
  =form_for(@current_user) do |f|
    -if @current_user.errors.any?
      #error_explanation
        %h2= pluralize(@ride.errors.count, "error")
        prohibited this ride from being saved:
        %ul
        -@ride.errors.full_messages.each do |msg|
          %li= msg

    .field
      = f.label "Name", :class => "label"
      .control
        = f.text_field :name, :class => "input"
    .field
      = f.label "Email", :class => "label"
      .control
        = f.text_field :email, :class => "input"
    .field.time-div
      = f.label "Would you like to receive email notifications?", :class => "label"
      .control
        = f.check_box :email_pref

    .actions
      = f.submit "Update profile", :class => "button is-info"
    

app/views/users/show.html.haml
=content_for :header do
  =render 'layouts/page_header', :title => "Your Rides"

- if @arrivals.length > 0
  .message.is-dark
    .message-header.has-background-grey-light
      %p Arrivals
    .message-body.has-background-white
      %table.table.is-striped.is-hoverable.is-fullwidth
        %thead
          %tr
            %th Arrival Day
            %th Arrival Time
            %th Riders
        %tbody
          - @arrivals.each do |ride|
            %tr
              %th
                =link_to ride.flighttime.strftime("%B %d, %Y"), ride_path(ride)
                -if ride.is_aspc
                  %span.tag.is-primary.is-rounded ASPC Free Ride Request
              %td
                =ride.flighttime.strftime("%I:%M %p")
              %td
                =ride.users.size

- if @departures.length > 0
  .message.is-dark
    .message-header.has-background-grey-light
      %p Departures
    .message-body.has-background-white
      %table.table.is-striped.is-hoverable.is-fullwidth
        %thead
          %tr
            %th Departure Day
            %th Ride Time
            %th Riders
        %tbody
          - @departures.each do |ride|
            %tr
              %th
                =link_to ride.flighttime.strftime("%B %d, %Y"), ride_path(ride)
                -if ride.is_aspc
                  %span.tag.is-primary.is-rounded ASPC Free Ride Request
              %td
                =ride.ridetime.strftime("%I:%M %p")
              %td
                =ride.users.size

- if @departures.length == 0 and @arrivals.length == 0
  %h2.subtitle
    It looks like you've booked no rides. Would you like to
    =link_to "create", new_ride_path
    or
    =link_to "join", root_path
    one?