config/routes.rb
Shuttleshare::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => 'rides#index'

  resources :rides do
    collection do
      get 'join'
      get 'leave'
      get 'airport'
      get 'aspc_rides'
    end

    resources :comments
  end

  resources :users do
    collection do
      get 'unsubscribe'
      get 'login'
    end
  end

  scope controller: :sessions do
    get   'unauthorized' => :not_authorized
    get   'login' => :new
    match 'logout' => :destroy, :via => [:get, :destroy]
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  post 'mailer/comment'

  #match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :rides_users
  has_many :users, :through => :rides_users
  has_many :comments, dependent: :destroy
  belongs_to :owner, :foreign_key => :owner_id, :class_name => 'User'

  accepts_nested_attributes_for :users
  attr_accessor :existing_aspc_ride

  validates :airport, :flighttime, :owner_id, :max_riders, :presence => true
  validate :is_flighttime_valid
  validate :is_aspc_valid

  def is_flighttime_valid
    return unless flighttime

    if flighttime < Time.now
      errors.add(:flighttime, "cannot be in the past")
    end
  end

  def is_aspc_valid
    return unless is_aspc

    # Change these depending on the program date
    # TODO: set this in admin panel
    aspc_ride_start_date = Date.new(2021, 12, 13)
    aspc_ride_end_date = Date.new(2021, 12, 18)

    if not flighttime.to_date.between? aspc_ride_start_date, aspc_ride_end_date
      errors.add(:flighttime, "falls outside the range of the program dates (#{aspc_ride_start_date.strftime("%B %d, %Y") + " - " + aspc_ride_end_date.strftime("%B %d, %Y")})")
    end

    users.each do |user|
      if Ride.joins(:users)
             .where(:is_aspc => true, :flighttime => aspc_ride_start_date..aspc_ride_end_date, :users => {:id => user.id})
             .count > 0

        errors.add(:users, "cannot join more than one ASPC funded ride at a time")
        break
      end
    end
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_filter :checker, :only => [:edit, :update, :destroy, :leave]
  before_filter :login_helper, :only => [:new, :join]

  before_filter do
    @title = "5C Rideshare"
  end

  def index
    @title = "5C Rideshare :: home"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @rides }
    end
  end

  def show
    @ride = Ride.find(params[:id])
    @ride_user = RidesUser.find_by(:ride => @ride, :user => @current_user)
    @users = @ride.users

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ride }
    end
  end

  def new
    @title = "5C Rideshare :: new"
    @ride = Ride.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ride }
    end
  end

  def edit
    @ride = Ride.find(params[:id])
    unless @ride.owner_id == @current_user.id
      redirect_to :back, :alert => "You did not create that ride, therefore you cannot edit it."
    end
  end

  def create
    @ride = Ride.new(ride_params)

    if @ride.is_aspc && @ride.existing_aspc_ride.present?
      return redirect_to join_rides_path(:id => @ride.existing_aspc_ride, :flighttime => @ride.flighttime)
    end

    @ride.owner_id = @current_user.id
    @ride.users << @current_user

    if @ride.is_aspc != true then @ride.is_aspc = false end

    respond_to do |format|
      if @ride.save

        @ride_user = RidesUser.find_by(:ride => @ride, :user => @current_user)
        @ride_user.flighttime = @ride.flighttime
        @ride_user.save

        current_user.phone_number = params[:phone_number]
        current_user.save

        notice_text = 'You successfully created a ride! When other riders comment, you\'ll get an email notification. Safe Travels!'
        if @ride.is_aspc
          notice_text = 'Your free ride request has been submitted to ASPC for processing. We will notify all applicants of their ride status soon. Thank you!'
        end

        format.html { redirect_to @ride, :notice => notice_text }
        format.json { render :json => @ride, :status => :created, :location => @ride }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ride.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @ride = Ride.find(params[:id])

    respond_to do |format|
      if @ride.update_attributes(ride_params)
        ride_user = RidesUser.find_by(:ride => @ride, :user => @ride.owner)
        ride_user.flighttime = @ride.flighttime
        ride_user.save

        format.html { redirect_to @ride, :notice => 'Ride was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ride.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @ride = Ride.find(params[:id])
    if @ride.owner_id == @current_user.id
      @ride.destroy

      respond_to do |format|
        format.html { redirect_to rides_url }
        format.json { head :ok }
      end
    else
      redirect_to root_url
    end
  end

  def join
    @ride = Ride.find(params[:id])


    unless @ride.users.find_by_id(@current_user.id)
      if @ride.users
        @ride.users.each do |user|
          if user.email && user.email_pref && user.email != "" && !@ride.is_aspc?
            begin
              UserMailer.new_rider_email(user, @current_user, url_for(@ride)).deliver
            rescue
              # Oops, an email error
            end
          end
        end
      end

      @ride.users << @current_user
      @ride.save

      if params[:flighttime]
        @ride_user = RidesUser.find_by(:ride => @ride, :user => @current_user)
        @ride_user.flighttime = params[:flighttime]
        @ride_user.save
      end

      respond_to do |format|

        notice_text = 'You successfully joined this ride. When other riders comment, you\'ll get an email notification. Safe Travels!'
        if @ride.is_aspc
          notice_text = 'Your free ride request has been submitted to ASPC for processing. We will notify all applicants of their ride status soon. Thank you!'
        end

        format.html { redirect_to @ride, :notice => notice_text }
        format.json { head :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to @ride, :alert => 'You already joined that ride!' }
        format.json { head :ok }
      end
    end
  end

  def leave
    @ride = Ride.find(params[:id])

    if @ride.users.find_by_id(@current_user.id)
      @ride.users.delete(@current_user)

      if(@ride.users.length == 0)
        @ride.destroy
      elsif @ride.owner_id == @current_user.id
        @ride.owner_id = @ride.users.first.id # Set a new owner upon owner leaving
        @ride.save
      end
    end

    respond_to do |format|
      format.html do
        if Ride.exists?(:id => params[:id])
          redirect_to :back
        else
          redirect_to :root
        end
      end
      format.json { head :ok }
    end
  end

  def aspc_rides
    airport = params[:airport]
    @rides = sort_rides(Ride.where(:airport => airport, :is_aspc => true).all)

    render :json => @rides
  end

  def airport
    info = airport_helper(params[:id])
    check = info[:check]

    @title = info[:title]
    @airport = info[:airport]
    @ftype = info[:ftype]
    @rides = info[:rides]
    @rides = sort_rides(@rides)
    @urides = @current_user.rides.to_set if @current_user
    if check
      respond_to do |format|
        format.html
        format.json {render :json => @rides}
      end
    else
      redirect_to root_url
    end
  end

  def airport_helper(type)
    case type
    when "1"
      {
      :title => "5C Rideshare :: to ontario",
      :airport => "To Ontario",
      :ftype => "Departure",
      :rides => Ride.where(airport: "To Ontario").all,
      :check => true
      }
    when "2"
      {
      :title => "5C Rideshare :: from ontario",
      :airport => "From Ontario",
      :ftype => "Arrival",
      :rides =>  Ride.where(airport: "From Ontario").all,
      :check => true
      }
    when "3"
      {
      :title => "5C Rideshare :: to LAX",
      :airport => "To LAX",
      :ftype => "Departure",
      :rides => Ride.where(airport: "To LAX").all,
      :check => true
      }
    when "4"
      {
      :title => "5C Rideshare :: from LAX",
      :airport => "From LAX",
      :ftype => "Arrival",
      :rides => Ride.where(airport: "From LAX").all,
      :check => true
      }
    when "5"
      {
      :title => "5C Rideshare :: to Burbank",
      :airport => "To Burbank",
      :ftype => "Arrival",
      :rides => Ride.where(airport: "To Burbank").all,
      :check => true
      }
    when "6"
      {
      :title => "5C Rideshare :: from Burbank",
      :airport => "From Burbank",
      :ftype => "Departure",
      :rides => Ride.where(airport: "From Burbank").all,
      :check => true
      }
    else
      {
        :check => false
      }
    end
  end

  private

  def ride_params
    if params[:ride]
      params.require(:ride).permit("airport", "flighttime(1i)", "flighttime(2i)", "flighttime(3i)", "flighttime(4i)", "flighttime(5i)",
      "ridetime(1i)","ridetime(2i)","ridetime(3i)","ridetime(4i)","ridetime(5i)", "is_aspc", "existing_aspc_ride", "max_riders")
    end
  end
end

app/views/rides/_form.html.erb
<% maxRiders = Hash.new
(1..8).each do |i|
  maxRiders[i.to_s] = i
  end
%>

<% if @current_user.school == "pomona" && false %>
  <div class="message is-info">
    <div class="message-header">
      As a Pomona Student, you're eligible for a free ride over winter break!
    </div>
    <div class="message-body">
      <div class="field is-grouped">
        <p class="control">
          <input type="checkbox" id="aspc-checkbox" />
        </p>
        <label class="label help">I would like to request a free ride to ONT/LAX funded by ASPC.</label>
      </div>
      <p class="is-size-7">
        <ul>
          <li>- You MUST be a Pomona College student.</li>
          <li>- Due to vehicle space limitations, we ask you limit the number of suitcases/luggage to 2 large items or 1 large + 2 small items</li>
          <li>- Not all departure times may receive transportation; this form’s purpose is to determine which Sagecoach and Sagehen Shuttle times should be finalized based on student ride demand!</li>
          <li>- Again, filling out this form does NOT guarantee a ride!!!</li>
        </ul>
        <br />
        <br />
        We will work to notify you of your assigned time as fast as we can. Thank you for your patience!
        <br />
        <br />
        <strong>This form closes at 5pm on November 22nd.</strong>
        <br />
        <br />
        Any comments, questions, or concerns can be sent to <a href="mailto:operations@aspc.pomona.edu">operations@aspc.pomona.edu</a>.
      </p>
    </div>
  </div>
<% end %>

<div id="non-aspc-free">
  <%= form_for(@ride) do |f| %>
    <% if @ride.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@ride.errors.count, "error") %></h2> prohibited this ride from being saved:

        <ul>
          <% @ride.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :is_aspc, :value => "false" %>
    </div>

    <div class="field">
      <%= f.label "Where are you going?", :class => 'label' %>
      <div class="control">
        <%= f.select :airport, ["To LAX", "To Ontario", "To Burbank", "From LAX", "From Ontario", "From Burbank"], {:selected => "2" }, {:class => 'select'} %>
      </div>
    </div>
    <div class="field">
      <%= f.label "What is the total maximum number of riders for the vehicle?", :class => 'label' %>
      <div class="control">
        <%= f.select :max_riders, maxRiders, {:selected => "1" }, {:class => 'select'} %>
      </div>
    </div>
    <div class="field">
      <%= f.label "When is your flight?", id: "js-flight-label", :class => 'label' %>
      <div class="control">
        <%= f.datetime_select :flighttime, { :order => [:day, :month, :year], :prompt => {:day => 'day', :month => "month", :year => "year", :hour => "hour", :minute => "minute", }, :ampm => true, :minute_step => 15, :start_year => 2021, :end_year => 2022 }, { :class => 'select' } %>
      </div>
    </div>
    <div class="field time-div">
      <%= f.label "When is the earliest time you’d be willing to leave for your flight?", :class => 'label' %>
      <div class="control">
        <%= f.datetime_select :ridetime, { :order => [:day, :month, :year], :prompt => {:day => 'day', :month => "month", :year => "year", :hour => "hour", :minute => "minute", }, :ampm => true, :minute_step => 15, :start_year => 2021, :end_year => 2022 }, { :class => 'select' } %>
      </div>
    </div>
    <div class="field">
      <%= f.label "What is your phone number?", :class => 'label' %>
      <div class="control">
        <%= number_field_tag :phone_number, nil, :class => 'input' %>
      </div>
    </div>
    <br />
    <div class="control">
      <%= f.submit :class => 'button is-primary' %>
    </div>
  <% end %>
</div>

<div id="aspc-free" style="display: none;">
  <%= form_for(@ride) do |f| %>
    <% if @ride.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@ride.errors.count, "error") %></h2> prohibited this ride from being saved:

        <ul>
          <% @ride.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :is_aspc, :value => "true" %>
    </div>

    <div class="field">
      <%= f.label "Where are you going?", :class => 'label' %>
      <div class="control">
        <%= f.select :airport, ["To LAX", "To Ontario"], {:selected => "2" }, {:class => 'select'} %>
      </div>
    </div>
    <div class="field">
      <%= f.label "What is the total maximum number of riders for the vehicle?", :class => 'label' %>
      <div class="control">
        <%= f.select :max_riders, maxRiders, {:selected => "1" }, {:class => 'select'} %>
      </div>
    </div>
    <div class="field">
      <%= f.label "When is your flight?", id: "js-flight-label", :class => 'label' %>
      <div class="control">
        <%= f.datetime_select :flighttime, { :order => [:day, :month, :year], :prompt => {:day => 'day', :month => "month", :year => "year", :hour => "hour", :minute => "minute", }, :ampm => true, :minute_step => 15, :start_year => 2021, :end_year => 2022 }, { :class => 'select' } %>
      </div>
    </div>

    <div class="field time-div" >
      <%= f.label "When is the earliest time you’d be willing to leave for your flight?", :class => "label" %>
      <div class="control">
        <%= f.datetime_select :ridetime, { :order => [:day, :month, :year], :prompt => {:day => 'day', :month => "month", :year => "year", :hour => "hour", :minute => "minute", }, :ampm => true, :minute_step => 15, :start_year => 2021, :end_year => 2022 }, { :class => 'select' } %>
      </div>
    </div>

    <div class="field">
      <%= f.label "What is your phone number?", :class => 'label' %>
      <div class="control">
        <%= number_field_tag :phone_number, nil, :class => 'input' %>
      </div>
    </div>

    <br />
    <div class="control">
      <%= f.submit :class => 'button is-primary' %>
    </div>
  <% end %>


</div>

<script>
  (function() {
      let nonAspcForm = $("#non-aspc-free")[0];
      let aspcForm = $("#aspc-free")[0];
      let aspcCheckbox = $("#aspc-checkbox");
      aspcCheckbox.click(function () {
          nonAspcForm.style.display = aspcCheckbox[0].checked ? "none" : "block";
          aspcForm.style.display = aspcCheckbox[0].checked ? "block" : "none";
      });
  })();
</script>

app/views/rides/airport.html.haml
=content_for :header do
  =render 'layouts/page_header', :title => "Available Rides #{@airport}"

- if @rides.select{|ride| !ride.is_aspc}.length > 0
  %table.table.is-striped.is-hoverable.is-fullwidth
    %thead
      %tr
        %th Ride Day
        %th Ride Time
        %th Riders
    %tbody
      - @rides.each do |ride|
        - unless ride.users.count == 0 || ride.is_aspc
          %tr
            %th
              %a{:href => ride_path(ride)}
                =ride.flighttime.strftime("%B %d, %Y")
            %td
              =ride.ridetime&.strftime("%I:%M %p") || "N/A"
            %td
              =ride.users.size
- else
  %h2.subtitle
    It looks like there are no rides to this airport right now. Would you like to
    =link_to "create one?", new_ride_path

app/views/rides/edit.html.erb
<%= content_for :header do %>
  <%= render 'layouts/page_header', :title => "Edit Ride Details" %>
<% end %>


<%= render 'form' %>

app/views/rides/index.html.haml
=content_for :header do
  =render 'layouts/page_header', :title => "5C Rideshare", :subtitle => "An ASPC Service"

.columns
  .column
    %p.title.is-4
      ASPC is excited to reintroduce the 5C Rideshare service!
    %p
      We know getting to and from the airport can be a hassle, so we're trying to make it easier for students at all of the Claremont Colleges to do so.
    %p
    The aim of this service is to allow students going to and from Ontario or LAX to connect with each other and split the cost of the ride – simply sign in and create or join a ride at a time which works for you!

%br

.columns
  .column
    #ride-search-bar-big
      .box.has-background-light
        .field.has-addons
          %p.control
            %a.button.is-static.is-large.has-background-white
              I'm looking for a shared ride... &nbsp;
          %p.control.is-expanded
            %span.select.is-fullwidth.is-large
              %select#airportSelect-big
                %option{:value => 1} To Ontario
                %option{:value => 2} From Ontario
                %option{:value => 3} To LAX
                %option{:value => 4} From LAX
                %option{:value => 5} To Burbank
                %option{:value => 6} From Burbank
          %p.control#goButton-big
            %a.button.is-link.is-large
              Go!
    #ride-search-bar-mobile
      %nav.panel
        %p.panel-heading
          I'm looking for a shared ride...
        .panel-block
          %span.select.is-fullwidth
            %select#airportSelect-mobile
              %option{:value => 1} To Ontario
              %option{:value => 2} From Ontario
              %option{:value => 3} To LAX
              %option{:value => 4} From LAX
              %option{:value => 5} To Burbank
              %option{:value => 6} From Burbank
        .panel-block
          %a.button.is-link.is-outlined.is-fullwidth#goButton-mobile
            Go!

%br

.columns
  .column
    .message.is-info
      - if false
        .message-header
          %p
            %strong POM STUDENTS ONLY:
            Free Rides to LAX/ONT During Finals Week
        .message-body
          %p
            The ASPC Rideshare Program is back and will be providing POMONA COLLEGE STUDENTS ONLY (of all class years) transportation (FREE OF CHARGE) from campus to LAX (Los Angeles International) and Ontario Airport on selected times during finals week.
          %p
            %strong
              For more details, sign in with your Pomona login and
              =link_to "request a ride.", new_ride_path

:javascript
  (function() {
    function goToSelectedPage(selector) {
      let airportId = $(selector).val();
      window.location.href = "#{airport_rides_url}?id=" + airportId;
    }

    $("#goButton-big").click(function() { goToSelectedPage("#airportSelect-big"); });
    $("#goButton-mobile").click(function() { goToSelectedPage("#airportSelect-mobile"); });
  })();

app/views/rides/new.html.haml
=content_for :header do
  =render 'layouts/page_header', :title => "Create a Ride"

#new-ride
  = render 'rides/form'

app/views/rides/show.html.erb
<%= content_for :header do %>
  <%= render 'layouts/page_header', :title => "Ride Details", :subtitle => "#{@ride.airport} on #{@ride.flighttime.strftime("%B %d, %Y")}" %>
<% end %>

<% if @ride.is_aspc %>
  <% if @ride_user %>
  <p class="subtitle">
    Thank you for requesting a free ride from ASPC. We are currently collecting and processing all requests, and we will send email confirmations by December 6th.
  </p>
  <p>
    Here is the information you have submitted – please contact us ASAP at <a href="mailto:product@aspc.pomona.edu">product@aspc.pomona.edu</a> if it is not correct.
    <br/><br />
    <table class="table is-bordered is-striped is-fullwidth">
      <tbody>
        <tr>
          <th>Name</th>
          <td><%= @ride_user.user.name %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @ride_user.user.email %></td>
        </tr>
        <tr>
          <th>Phone</th>
          <td><%= @ride_user.user.phone_number %></td>
        </tr>
        <tr>
          <th>Direction</th>
          <td><%= @ride.airport %></td>
        </tr>
        <tr>
          <th>Max Number of Riders</th>
          <td><%= @ride.max_riders %></td>
        </tr>
        <tr>
          <th>Flight Time</th>
          <td><%= @ride_user.flighttime.strftime("%l:%M%P on %B %d, %Y") %></td>
        </tr>
        <tr>
          <th>Earliest Preferred Ride Time</th>
          <td><%= @ride.ridetime&.strftime("%l:%M%P on %B %d, %Y") || "N/A" %></td>
        </tr>
      </tbody>
    </table>
  </p>
  <br />
  <br />
  <p class="is-size-7">
    Please note that your ride departure time is not yet finalized until we get back to you.
  </p>
  <br />
  <%= link_to 'Withdraw Free Ride Request', { :controller => "rides", :action => "leave", :id => @ride }, :confirm => "Are you sure you want to leave this ride?", :class => "button is-danger" %>
  <% else %>
    <p class="subtitle">
      You must be logged in and a member of this ride to view this page.
    </p>
  <% end %>

<% else  %>
<div class="columns">
  <div class="column">
    <p>
      <% if @ride.airport.split(" ")[0] == "To" && @ride.ridetime %>
        <b>Flight Departure:</b>
        <%= @ride.flighttime.strftime("%I:%M %p")%>
      <% else %>
        <b>Flight Arrival:</b>
        <%= @ride.flighttime.strftime("%I:%M %p")%>
      <% end %>
    </p>
  </div>
  <div class="column">
    <p>
      <b>Preferred ride time:</b>
      <%= @ride.ridetime&.strftime("%I:%M %p") || "N/A" %>
    </p>
  </div>
  <div class="column">
    <div class="has-text-right-tablet">
      <% if @current_user %>
        <% unless @ride.users.find_by_id(@current_user.id) %>
          <% if @users.length <= @ride.max_riders %> 
            <%= link_to 'Join Ride',{ :controller => "rides", :action => "join", :id => @ride }, :confirm => "Are you sure you want to join this ride?", :class => "button is-primary" %>
          <% end %>
        <% else %>
          <%= link_to 'Leave Ride', { :controller => "rides", :action => "leave", :id => @ride }, :confirm => "Are you sure you want to leave this ride?", :class => "button is-danger" %>
        <% end %>
        <% if @ride.owner_id == @current_user.id %>
          <%= link_to 'Edit', edit_ride_path(@ride), :class => "button is-lighter" %>
        <% end %>
      <% else %>
        <%= link_to 'Join Ride',{ :controller => "rides", :action => "join", :id => @ride }, :confirm => "You must sign in before you can join a ride. Would you like to sign in now?", :class => "button is-primary" %>
      <% end %>
    </div>
  </div>
</div>
<hr />

<div class="comments">
  <p><b>Current riders:</b></p>
  <% @users.each do |user| %>
    <span class="tag"><%= user.name %></span>
  <% end %>
  <br />
  <br />
  <% @ride.comments.each do |comment| %>
    <div class="message is-info">
    <div class="message-body">
    <%= render comment %>
    </div>
    </div>
  <% end %>
  <br />
  <% if @current_user %><%= render "comments/form" %><% end %>
</div>
<% end %>