config/routes.rb
Shuttleshare::Application.routes.draw do
  ActiveAdmin.routes(self)
  root :to => 'rides#index'

  resources :rides do
    collection do
      get 'join'
      get 'leave'
      get 'airport'
      get 'aspc_rides'
    end

    resources :comments
  end

  resources :users do
    collection do
      get 'unsubscribe'
      get 'login'
    end
  end

  scope controller: :sessions do
    get   'unauthorized' => :not_authorized
    get   'login' => :new
    match 'logout' => :destroy, :via => [:get, :destroy]
    match 'login/cas' => :create_via_cas, :via => [:get, :post]
    match 'login/credentials' => :create_via_credentials, :via => [:get, :post]
    match 'login/create_account' => :create_new_account, :via => [:get, :post]
  end

  post 'mailer/comment'

  #match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  #match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
end

app/views/layouts/_footer.html.haml
#footer-container
  © Associated Students of Pomona College
  %br
  %br
  :markdown
    Maintained by the [ASPC Software Development Group](https://pomonastudents.org/aspc/software).

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53783416-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.haml
%nav.navbar#application-header
  .navbar-brand
    %a.navbar-item{:href => '/5crideshare/'}
      %img{:src => asset_path('aspc_logo.png')}
      &nbsp;<strong>5C Rideshare</strong>

    .navbar-burger.burger
      %span
      %span
      %span

  .navbar-menu
    .navbar-start
      -if signed_in?
        =link_to "New Ride", new_ride_path, :class => "navbar-item"
        =link_to "Your Rides", user_path(@current_user), :class => "navbar-item"
        =link_to "Preferences", edit_user_path(@current_user), :class => "navbar-item"

    .navbar-end
      .navbar-item
        -if signed_in?
          =link_to "Logout", {:controller => "sessions", :action => "destroy"}, {:class => "button is-light"}
        -else
          =button_to 'Sign in', :login_cas, :class => 'button is-info'

:javascript
   $(document).ready(function () {
      $("#application-header .burger").click(function () {
          // Toggle the class on both the burger and the menu
          $(this).toggleClass('is-active');
          $("#application-header .navbar-menu").toggleClass('is-active');
      })
  });

app/views/layouts/_page_header.html.erb
<% title = local_assigns.fetch(:title) %>
<% subtitle = local_assigns.fetch(:subtitle, nil) %>

<section class="hero is-primary page-header">
  <div class="hero-body">
    <div class="container">
      <h1 class="title"><%= title %></h1>
      <% if subtitle %>
        <h2 class="subtitle">
          <%= raw subtitle %>
        </h2>
      <% end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag asset_path('aspc_logo.png') %>
  <meta property="og:title" content="5C Rideshare" />
  <meta property="og:description" content="Find rides to and from the airport at the Claremont Colleges." />
  <meta property="fb:app_id" content="300857556614018"/>
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="http://5crideshare.com"/>
  <meta property="og:image" content='<%= image_url "og_image" %>'/>
</head>
<body>
  <div id="fb-root"></div>

  <script>
    var current_user_id = <%=
      if @current_user
        @current_user.id
      else -1
      end%>
  </script>


  <%= render 'layouts/header'%>

  <%if flash[:notice]%>
    <p class = "notice">
      <%=notice%><br>
      <%=flash[:notice_subtitle]%>
    </p>
  <%end%>
  <%if flash[:end]%>
    <p class = "alert">
      <%=alert%>
    </p>
  <%end%>

  <section class="section application-body-container">
    <%= yield :header %>
    <section class="section application-content-section">
      <div class="container application-content-container">
        <%= yield %>
      </div>
    </section>
  </section>

  <%= render 'layouts/footer'%>
  <%= render 'layouts/ga' if Rails.env.production?%>
</body>
</html>